### ISSUE TITLE
Bower package not available?

### ISSUE THREAD

**Issue by jperals** [epistemex/cardinal-spline-js#4]
Running the command `bower install cardinal-spline-js` as stated in the Readme fails with this output:

```bower                        ENOTFOUND Package cardinal-spline-js not found```

Then I also noticed that:

- There seems to be no `bower.json` file in this repository.
- Searching for `cardinal-spline-js` on https://bower.io/search/ also gives no result.

**Comment by epistemex** [comment]
Added bower package file. It turns out not to be registered (the readme uses a template) but should be now. Thanks for reporting.
